_wandb:
    value:
        cli_version: 0.25.0
        e:
            bk9dly56ggzgy2gzt186gg5kczsbq862:
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "48891371520"
                        used: "35959271424"
                email: comyn.bram@gmail.com
                executable: /home/bram/ugent/software-engineering-lab-3/brittle-star-locomotion/.venv/bin/python3
                git:
                    commit: c14606d7107992a1b81fd186268d932de70ac9fe
                    remote: git@github.com:bramcomyn/software-engineering-lab-3.git
                gpu: NVIDIA GeForce RTX 3050 Ti Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2560
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Ti Laptop GPU
                      uuid: GPU-34e76893-78b0-5c84-9a7e-7f8318f64b21
                host: gandalf
                memory:
                    total: "15956148224"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: -m __main__
                python: CPython 3.12.3
                root: /home/bram/ugent/software-engineering-lab-3/brittle-star-locomotion
                startedAt: "2026-03-26T10:03:46.414438Z"
                writerId: bk9dly56ggzgy2gzt186gg5kczsbq862
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 12
                - 45
            "2":
                - 12
                - 45
            "3":
                - 13
                - 16
                - 61
            "4": 3.12.3
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
batch_size:
    value: 32
discount:
    value: 0.99
epsilon:
    value: 1
epsilon_decay:
    value: 0.95
epsilon_min:
    value: 0.01
n_episodes:
    value: 50
