repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml

-   repo: https://github.com/astral-sh/uv-pre-commit
    # Update to the latest version of uv
    rev: 0.5.15 # Check for the latest version
    hooks:
        - id: uv-lock
